### ISSUE TITLE
blockstore-core/base not found after installing blockstore-core

### ISSUE THREAD

**Issue by unrival-protocol** [ipfs/js-blockstore-core#10]
I installed `ipfs-core` in a Vue project and tried serving the app.  I get the following error:

```
This dependency was not found:

* blockstore-core/base in ./node_modules/blockstore-datastore-adapter/cjs/src/index.js, ./node_modules/ipfs-bitswap/cjs/src/bitswap.js

To install it, you can run: npm install --save blockstore-core/base

```

I tried installing `blockstore-core/base` as suggested, but it's not found.  I also installed `blockstore-core`, but this didn't help.

Here's what my package.json looks like:

```
{
  "name": "test",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "serve": "vue-cli-service serve",
    "build": "vue-cli-service build",
    "lint": "vue-cli-service lint"
  },
  "dependencies": {
    "blockstore-core": "^1.0.3",
    "core-js": "^3.8.3",
    "ganache": "^6.4.5",
    "ipfs-core": "0.12.2",
    "vue": "^2.6.11",
    "vue-router": "^3.2.0",
    "vuex": "^3.4.0",
    "web3": "^1.6.1"
  },
  "devDependencies": {
    "@vue/cli": "^4.5.15",
    "@vue/cli-plugin-babel": "~4.5.0",
    "@vue/cli-plugin-eslint": "~4.5.0",
    "@vue/cli-plugin-router": "~4.5.0",
    "@vue/cli-plugin-vuex": "~4.5.0",
    "@vue/cli-service": "~4.5.0",
    "@vue/cli-service-global": "^4.5.15",
    "babel-eslint": "^10.1.0",
    "eslint": "^6.7.2",
    "eslint-plugin-vue": "^6.2.2",
    "vue-template-compiler": "^2.6.11"
  }
}
```

Am I doing something wrong?

**Comment by joeangel** [comment]
- `blockstore-core@1.0.3` is same here
- I'm using `blockstore-core@1.0.2` works well
  - `npm i blockstore-core@1.0.2`

**Comment by unrival-protocol** [comment]
@joeangel   Downgrading made the problem go away.  Thanks.

**Comment by deanpress** [comment]
This only works when installing with `npm i blockstore-core@1.0.2`. Not when including it in dependencies.

**Comment by joeangel** [comment]
I'm not sure the reason that 1.0.3 isn't working and guess that maybe its's related with cjs/ejs.

Maybe there are two ways can solve the problem:

1. downgrade to `blockstore-core@1.0.2`
2. using ejs style in your project with `blockstore-core@1.0.3`

---
(Observe more)

Showing how I found the situation:

- `blockstore-core@1.0.2` using csj in package.json `"main": "./cjs/src/index.js"`
- `blockstore-core@1.0.3` using ejs in package.json `"main": "./src/index.js"`

I'm using the package `nft.storage`.

```=
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main defined in /Users/joe/git/my-project/node_modules/blockstore-core/package.json
    at new NodeError (node:internal/errors:371:5)
    at throwExportsNotFound (node:internal/modules/esm/resolve:440:9)
    at packageExportsResolve (node:internal/modules/esm/resolve:645:7)
    at resolveExports (node:internal/modules/cjs/loader:482:36)
    at Function.Module._findPath (node:internal/modules/cjs/loader:522:31)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:919:27)
    at Module.Hook._require.Module.require (/Users/joe/git/my-project/node_modules/require-in-the-middle/index.js:61:29)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/joe/git/my-project/node_modules/ipfs-car/dist/cjs/blockstore/memory.js:5:27)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at Module.Hook._require.Module.require (/Users/joe/git/my-project/node_modules/require-in-the-middle/index.js:80:39)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/joe/git/my-project/node_modules/ipfs-car/dist/cjs/pack/index.js:12:18)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at Module.Hook._require.Module.require (/Users/joe/git/my-project/node_modules/require-in-the-middle/index.js:80:39)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/joe/git/my-project/node_modules/nft.storage/dist/src/lib.cjs:8:12)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)                                                                                                               [0/335]
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at Module.Hook._require.Module.require (/Users/joe/git/my-project/node_modules/require-in-the-middle/index.js:80:39)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/joe/git/my-project/node_modules/nft.storage/dist/src/lib.cjs:8:12)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at Module.Hook._require.Module.require (/Users/joe/git/my-project/node_modules/require-in-the-middle/index.js:80:39)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/joe/git/my-project/models/ipfs/ipfs.js:5:30)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at Module.Hook._require.Module.require (/Users/joe/git/my-project/node_modules/require-in-the-middle/index.js:80:39)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/joe/git/my-project/routes/index.js:61:14)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at Module.Hook._require.Module.require (/Users/joe/git/my-project/node_modules/require-in-the-middle/index.js:80:39)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/joe/git/my-project/app.js:75:11)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/joe/git/my-project/server.js:4:11)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
```

Notice the two lines:

- `"exports" main defined in /Users/joe/git/my-project/node_modules/blockstore-core/package.json`
  - `blockstore-core` cannot be used in my project for some unknown reason
- `at Object.<anonymous> (/Users/joe/git/tms-for-release/node_modules/ipfs-car/dist/cjs/blockstore/memory.js:5:27)`
  - `const blockstore_core_1 = require("blockstore-core");` in `node_modules/ipfs-car/dist/cjs/blockstore/memory.js:5`
  - seems trying to load using cjs style to access the packge `blockstore-core`
    - but `blockstore-core@1.0.3` is using ejs style (in package.json `"main": "./src/index.js"`)

**Comment by ljmf00** [comment]
Same happening on my IPFS car pipeline https://github.com/ljmf00/tasks/runs/4738924841

**Comment by ukstv** [comment]
@achingbrain It is release via `semantic-release` that broke the package. I guess `aegir` previously took care of cjs/esm/et al stuff in `/dist` folder, along with proper `package.json`. The last released package disregarded it all.

**Comment by roderik** [comment]
Ran into this as well, quick fix for yarn users.

```
  "resolutions": {
    "blockstore-core": "1.0.2"
  }
```

**Comment by achingbrain** [comment]
Ah, sorry - I missed this issue.

I’ve just published a new version that should resolve the issue - please try again and ensure you get blockstore-core@1.0.5.

**Comment by ljmf00** [comment]
> Ah, sorry - I missed this issue.
> 
> I’ve just published a new version that should resolve the issue - please try again and ensure you get blockstore-core@1.0.5.

I can confirm this is solved. Feel free to close.
